-- local swap = require('nvim-treesitter-textobjects.swap')
-- local move = require('nvim-treesitter-textobjects.move')
--
-- local nmap = function (key, fn, desc)
-- 	vim.api.set("n", key, fn, desc)
-- end
--
-- nmap("<leader>a", function() swap.swap_next("@parameter.inner") end)
-- nmap("<leader>A", function() swap.swap_previous("@parameter.inner") end)
--
-- nmap("]f", function() move.goto_next_start("@function.outer") end)
-- nmap("]c", function() move.goto_next_start("@class.outer") end)
-- nmap("]p", function() move.goto_next_start("@parameter.outer") end)
-- nmap("]P", function() move.goto_next_start("@parameter.inner") end)
--
-- nmap("[f", function() move.goto_previous_start("@function.outer") end)
-- nmap("[c", function() move.goto_previous_start("@class.outer") end)
-- nmap("[p", function() move.goto_previous_start("@parameter.outer") end)
-- nmap("[P", function() move.goto_previous_start("@parameter.inner") end)
